#statefulset
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: ingesta-elk   # ingesta-elk0 y ingesta-elk1   
spec:
    replicas: {{ .Values.ingesta.pod.replicas }}
    selector:
        matchLabels:
            app: ingesta-elk    
    serviceName: {{ .Values.ingesta.service.nombre }}
    template:
        metadata:
            labels:
                app: ingesta-elk
        spec:
            containers:
                -   name:   elasticsearch
                    image:  {{ .Values.cluster.imagenes.elasticsearch }}:{{ .Values.cluster.imagenes.version }}
                    env:
                          - name:   node.name
                            valueFrom:  
                                fieldRef:
                                    fieldPath: metadata.name
                          - name:   cluster.name
                            valueFrom:
                                configMapKeyRef:
                                    name:   {{ .Values.ingesta.configMap.nombre }}
                                    key:    NOMBRE_CLUSTER                      
                          - name:   discovery.seed_hosts
                            value:  maestro-elk                        
                          - name:   ES_JAVA_OPTS
                            valueFrom:
                                configMapKeyRef:
                                    name:   {{ .Values.ingesta.configMap.nombre }}
                                    key:    MEMORIA_JAVA
                          - name:   node.master 
                            value:  "false"
                          - name:   node.voting_only
                            value:  "false"                          
                          - name:   node.data
                            value:  "false"                          
                          - name:   node.ingest
                            value:  "true"
                          - name:   node.remote_cluster_client
                            value:  "false"                           

                    ports:
                        - containerPort:  {{ .Values.cluster.puerto }}
                    volumeMounts:
                        -   name:   pvc-ingesta-elk
                            mountPath: {{ .Values.cluster.persistencia.rutaDatosEnImagen }}
                    
    volumeClaimTemplates:
        -   metadata:
                name: pvc-ingesta-elk
            spec:
                storageClassName:   {{ .Values.cluster.persistencia.storageClass }}
                resources:
                    requests:
                        storage:    {{ .Values.ingesta.pod.storage }}
                accessModes:
                    - ReadWriteOnce
            