
kind: Service
apiVersion: v1
metadata:
    name: {{ .Values.maestro.servicio.nombre }}                   ######
spec:
    type: ClusterIP 
    ports:
        - # La definicion de mapeos de puertos 
            name: externo
            targetPort: {{ .Values.cluster.puerto }}            ######
            port: {{ .Values.cluster.puerto }}
        - # La definicion de mapeos de puertos 
            name: interno
            targetPort: {{ .Values.cluster.puertoInterno }}            ######
            port: {{ .Values.cluster.puertoInterno }}
    selector:
        app: maestro-elk
