
kind: Service
apiVersion: v1
metadata:
    name: maestro-elk
spec:
    type: ClusterIP 
    ports:
        - # La definicion de mapeos de puertos 
            name: externo
            targetPort: 9200 
            port: 9200
        - # La definicion de mapeos de puertos 
            name: interno
            targetPort: 9300
            port: 9300
    selector:
        app: maestro-elk
