
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: maestro-elk         # maestro-elk-0     maestro-elk-1
spec:
    replicas:       {{ .Values.maestro.pod.replicas }}
    selector:
        matchLabels:
            app:    maestro-elk
    serviceName:    {{ .Values.maestro.servicio.nombre }}
    template:
        metadata:
            labels:
                app: maestro-elk
        spec:
            containers:
                -   name:               elasticsearch
                    image:              {{ .Values.cluster.imagenes.elasticsearch }}:{{ .Values.cluster.imagenes.version }}
                    env:
                      -     name: node.name
                            valueFrom:
                                fieldRef:
                                    fieldPath:  metadata.name               # Nombre de pod
                      -     name: cluster.name
                            valueFrom:
                                configMapKeyRef:
                                    name:   {{ .Values.maestro.configMap.nombre }}
                                    key:    NOMBRE_CLUSTER
                      -     name: discovery.seed_hosts
                            value: maestro-elk-0.{{ .Values.maestro.servicio.nombre }},maestro-elk-1.{{ .Values.maestro.servicio.nombre }}           
                      -     name: cluster.initial_master_nodes
                            value: maestro-elk-0, maestro-elk-1     # Nombre de nodos (en ES) que optarán en primer lugar a ser maestros  
                      -     name: ES_JAVA_OPTS
                            valueFrom:
                                configMapKeyRef:
                                    name:   {{ .Values.maestro.configMap.nombre }}
                                    key:    MEMORIA_JAVA
                      -     name: node.master
                            value: "true"
                      -     name: node.voting_only
                            value: "false"
                      -     name: node.data
                            value: "false"
                      -     name: node.ingest
                            value: "false"
                      -     name: node.remote_cluster_client
                            value: "false"
                    ports:
                        - containerPort: {{ .Values.cluster.puerto }}
                        - containerPort: {{ .Values.cluster.puertoInterno }}
                    volumeMounts:
                        -   name:       pvc-maestro-elk
                            mountPath:  {{ .Values.cluster.persistencia.rutaDatosEnImagen }}
    volumeClaimTemplates:
        -   metadata:
                name: pvc-maestro-elk
            spec:
                storageClassName: {{ .Values.cluster.persistencia.storageClass }}
                resources:
                    requests:
                        storage: {{ .Values.maestro.pod.espacioAlmacenamiento }}
                accessModes:
                    - ReadWriteOnce
    

