# Admisnitrador
kind: PersistentVolume
apiVersion: v1
metadata:
    name: volumen-mariadb

spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteOnce # Un volumen que quiero donde poder escribir solo yo
        - ReadWriteMany # Un volumen que se puede entregar a muchos pods
    storageClassName: rapidito-redundante
    
    hostPath:
        type: DirectoryOrCreate
        path: /home/ubuntu/environment/datos/mariadb
    # Politica de reciclaje de datos
        # El volumen se borra al desvincularse
        # El volumen (los datos) se mantienen al desvincularse
