
# Desarrollador
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
    name: peticion-volumen-mariadb

spec:
#        Tamaño           50Gbs
    resources:
        requests:
            storage: 1Gi
    accessModes:
        - ReadWriteOnce # Un volumen que quiero donde poder escribir solo yo
#        - ReadWriteMany # Un volumen que se puede entregar a muchos pods
#        - ReadOnceMany  # Un volumen que se puede entregar a muchos pods solo para lectura
    storageClassName: rapidito-redundante
#        Rendimiento      ALTO
#        Replicación      SI   RAID ESPEJO
#        Encripción       NO

