kind:           Deployment
apiVersion:     apps/v1

metadata:
    name:       wordpress

spec:
    replicas: 1
    
    selector:
        matchLabels:
            app: wordpress
            
    template:
        metadata:
            name:       wordpress-template
            labels:
                app:    wordpress
        
        spec:
            containers:
                - name:         wordpress
                  image:        wordpress:latest
                  env:
                    - name:     WORDPRESS_DB_HOST
                      value:    mariadb
                      
                    - name:     WORDPRESS_DB_USER
                      valueFrom:    
                        configMapKeyRef:
                            name: datos-bbdd
                            key:  DB_USER
                            
                    - name:     WORDPRESS_DB_PASSWORD
                      valueFrom:    
                        secretKeyRef:
                            name: datos-bbdd
                            key:  DB_PASSWORD
                            
                    - name:     WORDPRESS_DB_NAME
                      valueFrom:    
                        configMapKeyRef:
                            name: datos-bbdd
                            key:  DATABASE
                            
                    - name:     WORDPRESS_TABLE_PREFIX
                      valueFrom:    
                        configMapKeyRef:
                            name: datos-bbdd
                            key:  TABLE_PREFIX
                            
                  ports:
                    - containerPort: 80
                  volumeMounts:
                    - name:         datos
                      mountPath:    /var/www/html
                  resources:
                    requests:   # 
                        cpu: 500m
                        memory: 500Mi
                    limits:
                        cpu: 1
                        memory: 1000Mi
            volumes:
                - name:             datos
                  persistentVolumeClaim:
                    claimName:      peticion-volumen-wordpress
